### ISSUE TITLE
Comparison to 'block processing' of rows

### ISSUE THREAD

**Issue by PeteHaitch** [LTLA/flmam#1] opened 2018-09-20 05:15 UTC
Hi Aaron,

I'm experimenting with **flmam** to fit linear models to very long (10-100 million rows, 10-100 columns) HDF5-backed *DelayedMatrix* objects.
In some brief experiments, I found that the simple strategy of reading in multiple rows of data into memory as an ordinary *matrix* and then running `flmam::fitLM()` (or `limma::lmFit()`) and combining the output was notably faster than calling `flmam::fitLM()` with an equivalent number of cores (likely at the expense of increased memory usage on the worker, but that's an ok tradeoff for me). 

That leaves me wondering where you think **flmam** fits in. Could it also load in multiple rows and get the same benefit or do you want/need to stick to a one-row-at-a-time approach?

Cheers,
Pete

Here, I'm using an example with 100,000 rows and 100 columns. 

``` r
suppressPackageStartupMessages(library(flmam))
suppressPackageStartupMessages(library(HDF5Array))
library(microbenchmark)

set.seed(666)
y <- matrix(rnorm(10000000), ncol = 100)
Y <- realize(y, "HDF5Array")
covariate <- runif(ncol(y))
design <- model.matrix(~covariate)

g <- function() fitLM(y, design, BPPARAM = SerialParam())
G <- function() fitLM(Y, design, BPPARAM = SerialParam())
G_mc <- function() fitLM(Y, design, BPPARAM = MulticoreParam(workers = 3))
H <- function() {
    y <- as.matrix(Y)
    fitLM(y, design, BPPARAM = SerialParam())
}
H_loop <- function() {
    subset <- split(
        x = seq_len(nrow(Y)),
        f = cut(seq_len(nrow(Y)), 6, labels = FALSE))
    ans <- bplapply(subset, function(s) {
        YY <- as.matrix(Y[s, , drop = FALSE])
        fitLM(YY, design, BPPARAM = SerialParam())
    }, BPPARAM = SerialParam())
    do.call(rbind, ans)
}
H_loop_mc <- function() {
    subset <- split(
        x = seq_len(nrow(Y)),
        f = cut(seq_len(nrow(Y)), 6, labels = FALSE))
    ans <- bplapply(subset, function(s) {
        YY <- as.matrix(Y[s, , drop = FALSE])
        fitLM(YY, design, BPPARAM = SerialParam())
    }, BPPARAM = MulticoreParam(workers = 3))
    do.call(rbind, ans)
}


all.equal(g(), G())
#> [1] TRUE
all.equal(g(), G_mc())
#> [1] TRUE
all.equal(g(), H())
#> [1] TRUE
all.equal(g(), H_loop())
#> [1] TRUE
all.equal(g(), H_loop_mc())
#> [1] TRUE

microbenchmark(g(), G(), G_mc(), H(), H_loop(), H_loop_mc(), times = 10)
#> Unit: milliseconds
#>         expr       min        lq      mean    median        uq       max
#>          g()  129.8948  150.2309  168.9941  161.4129  197.8682  205.2677
#>          G() 3213.4711 3414.5852 3573.2241 3543.1196 3646.7430 4132.1779
#>       G_mc() 2887.6424 2909.2093 3050.2629 3067.6229 3103.0581 3259.3239
#>          H()  972.9111 1039.8979 1128.7753 1100.3225 1149.3194 1434.0171
#>     H_loop() 2058.6559 2125.0759 2214.8739 2186.6123 2276.2862 2417.9459
#>  H_loop_mc() 1166.0729 1205.6040 1296.3367 1277.2697 1359.6903 1468.3594
#>  neval   cld
#>     10 a    
#>     10     e
#>     10    d 
#>     10  b   
#>     10   c  
#>     10  b
```

<sup>Created on 2018-09-20 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

<details>

<summary>Session info</summary>

``` r
devtools::session_info()
#> Session info -------------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  system   x86_64, darwin15.6.0        
#>  ui       X11                         
#>  language (EN)                        
#>  collate  en_AU.UTF-8                 
#>  tz       Australia/Melbourne         
#>  date     2018-09-20
#> Packages -----------------------------------------------------------------
#>  package        * version date       source                     
#>  backports        1.1.2   2017-12-13 CRAN (R 3.5.0)             
#>  base           * 3.5.1   2018-07-05 local                      
#>  BiocGenerics   * 0.27.1  2018-06-17 Bioconductor               
#>  BiocParallel   * 1.15.12 2018-09-13 Bioconductor               
#>  codetools        0.2-15  2016-10-05 CRAN (R 3.5.1)             
#>  compiler         3.5.1   2018-07-05 local                      
#>  datasets       * 3.5.1   2018-07-05 local                      
#>  DelayedArray   * 0.7.41  2018-09-14 Bioconductor               
#>  devtools         1.13.6  2018-06-27 CRAN (R 3.5.0)             
#>  digest           0.6.17  2018-09-12 CRAN (R 3.5.1)             
#>  evaluate         0.11    2018-07-17 CRAN (R 3.5.0)             
#>  flmam          * 0.98.1  2018-09-20 Github (LTLA/flmam@f9cf174)
#>  graphics       * 3.5.1   2018-07-05 local                      
#>  grDevices      * 3.5.1   2018-07-05 local                      
#>  grid             3.5.1   2018-07-05 local                      
#>  HDF5Array      * 1.9.19  2018-09-14 Bioconductor               
#>  htmltools        0.3.6   2017-04-28 CRAN (R 3.5.0)             
#>  IRanges        * 2.15.17 2018-08-24 Bioconductor               
#>  knitr            1.20    2018-02-20 CRAN (R 3.5.0)             
#>  lattice          0.20-35 2017-03-25 CRAN (R 3.5.1)             
#>  magrittr         1.5     2014-11-22 CRAN (R 3.5.0)             
#>  MASS             7.3-50  2018-04-30 CRAN (R 3.5.1)             
#>  Matrix           1.2-14  2018-04-13 CRAN (R 3.5.1)             
#>  matrixStats    * 0.54.0  2018-07-23 CRAN (R 3.5.1)             
#>  memoise          1.1.0   2017-04-21 CRAN (R 3.5.0)             
#>  methods        * 3.5.1   2018-07-05 local                      
#>  microbenchmark * 1.4-4   2018-01-24 CRAN (R 3.5.0)             
#>  multcomp         1.4-8   2017-11-08 CRAN (R 3.5.0)             
#>  mvtnorm          1.0-8   2018-05-31 CRAN (R 3.5.0)             
#>  parallel       * 3.5.1   2018-07-05 local                      
#>  Rcpp             0.12.18 2018-07-23 CRAN (R 3.5.1)             
#>  rhdf5          * 2.25.9  2018-09-04 Bioconductor               
#>  Rhdf5lib         1.3.3   2018-09-03 Bioconductor               
#>  rmarkdown        1.10    2018-06-11 CRAN (R 3.5.0)             
#>  rprojroot        1.3-2   2018-01-03 CRAN (R 3.5.0)             
#>  S4Vectors      * 0.19.19 2018-07-18 Bioconductor               
#>  sandwich         2.5-0   2018-08-17 CRAN (R 3.5.0)             
#>  splines          3.5.1   2018-07-05 local                      
#>  stats          * 3.5.1   2018-07-05 local                      
#>  stats4         * 3.5.1   2018-07-05 local                      
#>  stringi          1.2.4   2018-07-20 CRAN (R 3.5.1)             
#>  stringr          1.3.1   2018-05-10 CRAN (R 3.5.0)             
#>  survival         2.42-6  2018-07-13 CRAN (R 3.5.0)             
#>  TH.data          1.0-9   2018-07-10 CRAN (R 3.5.0)             
#>  tools            3.5.1   2018-07-05 local                      
#>  utils          * 3.5.1   2018-07-05 local                      
#>  withr            2.1.2   2018-03-15 CRAN (R 3.5.0)             
#>  yaml             2.2.0   2018-07-25 CRAN (R 3.5.1)             
#>  zoo              1.8-4   2018-09-19 CRAN (R 3.5.1)
```

</details>

**Comment by LTLA** [comment] 2018-09-20 08:19
_beachmat_'s HDF5 handling is a bit wonky right now due to bug in the HDF5 source introduced in 1.10.3, see https://forum.hdfgroup.org/t/unintended-behaviour-for-hash-values-during-chunk-caching/4869/3. Do you get the same timings for other matrix representations, e.g., sparse matrices?

**Comment by PeteHaitch** [comment] 2018-09-20 08:34
I've not tried but can (although my data are dense doubles)

**Comment by LTLA** [comment] 2018-09-20 08:46
You can also try setting up the chunks so that each chunk encompasses all columns. This should avoid the buggy behaviour for the time being. There is no guaranteed patch on our side, it needs to be fixed in the HDF5 source directly. (I guess we could ask @grimbough to modify the _Rhdf5lib_ source, though that may have unintended consequences and I really wouldn't like us taking responsibility for doing that.)

**Comment by PeteHaitch** [comment] 2018-09-20 10:27
Yeah, i don't think we should diverge from the HDF5 source.

**Comment by LTLA** [comment] 2018-09-24 13:50
Having looked at this further, I believe that the chunk caching bug in the HDF5 source is **not** the cause of the slow-down here. Rather, it seems to be something to do with (unskippable) data re-organization within the HDF5 API when the output `DataSpace` does not have the same dimensionality as the input `DataSpace`. This reduces performance unnecessarily, see LTLA/beachmat#10 for a similar scenario.

If we force the same dimensions to be used within _beachmat_, I get timings like this:

```
> microbenchmark(g(), G(), H_loop(), times = 10)
Unit: milliseconds
     expr       min         lq      mean     median         uq        max neval
      g()   77.5645   78.24351   80.4314   78.90991   79.53385   95.42194    10
      G() 1042.8958 1061.49376 1079.6224 1066.36999 1094.09602 1146.33482    10
 H_loop() 1176.8964 1204.23498 1229.0288 1214.01236 1252.35115 1308.92073    10
```

Try installing the `modhdf5` branch on https://github.com/LTLA/beachmat. You may have to re-install _flmam_, I don't think R packages are set up for shared libraries on Macs.

**P.S.** Obviously, for a fair comparison w.r.t. memory, one should do the `cut` in `H_loop()` to yield block sizes equivalent to the total size of all chunks overlapping a row. When one does so, you should see that `H_loop` is much slower, which is to be expected due to 1000 loop iterations in R.

**Comment by LTLA** [comment] 2018-09-27 09:57
@PeteHaitch Can you reproduce the timings above? If so, I will merge the _beachmat_ branch.

**Comment by PeteHaitch** [comment] 2018-09-27 10:54
With the `modhdf5` branch of **beachmat** and having re-installed **flmam** I get:

```R
> microbenchmark(g(), G(), H_loop(), times = 10)
Unit: milliseconds
     expr      min        lq      mean    median       uq       max neval cld
      g()  104.534  106.1959  128.7978  107.9704  151.474  226.3562    10  a 
      G() 1647.382 1708.1895 1790.9689 1732.7100 1796.232 2324.2388    10   b
 H_loop() 1734.550 1801.4806 1845.2049 1829.5392 1903.614 2007.7619    10   b
```

**Comment by LTLA** [comment] 2018-09-27 11:58
Okay, merged.

**Closed as completed by LTLA** 2018-09-27 11:58 UTC
